### ISSUE TITLE
Context menu of favorites not selectable

### ISSUE THREAD

**Issue by mor0012m** [fthx/dash-from-panel#2]
If I press the right mouse button on a favorite, the context menu pops up, but vanishes almost everytime before I can select a menu entry, eg. I was never able to select chrome to open an incognito window from the context menu. In dock to dash it simply works ...

**Comment by fthx** [comment]
That's because of GS 42 changes in hover/focus/grab.
The solution is done in dock from dash extension.

I will not update this one.

**Comment by fthx** [comment]
That's solved now with the major version that will land for update very soon.
Already updated here, with prefs UI!
@martinPL
